#!/usr/bin/env python3
"""Contributor credits generator — used at release time.

Generates a markdown credits section from git history since the last tag,
so every release publicly credits its contributors (GOVERNANCE.md promise).

Usage:
  python scripts/contributors_credits.py            # since last tag
  python scripts/contributors_credits.py v1.4.0     # since explicit ref
"""
from __future__ import annotations

import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

BOT_AUTHORS = {
    "dependabot[bot]",
    "github-actions[bot]",
    "devin-ai-integration[bot]",
}


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def last_tag() -> str:
    try:
        return _git("describe", "--tags", "--abbrev=0")
    except subprocess.CalledProcessError:
        return _git("rev-list", "--max-parents=0", "HEAD")[:12]


def main() -> int:
    base = sys.argv[1] if len(sys.argv) > 1 else last_tag()
    log_format = "%aN <%aE>"
    authors_raw = _git("log", f"{base}..HEAD", f"--format={log_format}")
    commits_by_author = Counter(authors_raw.splitlines())

    # Coalesce by email identity (same person, different names)
    by_email: dict[str, str] = {}
    counts: Counter[str] = Counter()
    for line in commits_by_author.elements():
        name, _, email = line.rpartition(" <")
        email = email.rstrip(">")
        display = name.strip()
        if not by_email.get(email):
            by_email[email] = display
        counts[email] += 1

    print(f"## Contributors (since {base})\n")
    total = 0
    for email, n in counts.most_common():
        display = by_email[email]
        if display in BOT_AUTHORS or email in {"actions@github.com"}:
            continue
        total += n
        handle = ""
        print(f"- **{display}** — {n} commit{'s' if n > 1 else ''}{handle}")
    if total == 0:
        print("- (no human commits in range)")
    print(
        "\nGenerated by `scripts/contributors_credits.py` — "
        "paste into the GitHub Release notes."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
