"""
Tests for automated API documentation generation (NDBG-9).

Verifies that pdoc builds without errors and that all main public methods
of NeuralDbg appear in the generated output.
"""

import subprocess
import sys

import pytest

# Public methods that the acceptance criteria require to be documented
REQUIRED_METHODS = [
    "record_loss",
    "explain_failure",
    "get_causal_hypotheses",
    "trace_causal_chain",
    "detect_coupled_failures",
    "get_root_causes",
    "get_events",
    "step_iteration",
    "export_aquarium_package",
    "export_mermaid_causal_graph",
]


def _pdoc_available() -> bool:
    try:
        import pdoc  # noqa: F401

        return True
    except ImportError:
        return False


@pytest.mark.skipif(not _pdoc_available(), reason="pdoc not installed")
class TestDocsBuild:
    """Verify pdoc generates docs without errors."""

    def test_docs_build_exits_zero(self, tmp_path):
        """pdoc neuraldbg exits 0 (no errors, no missing docstrings)."""
        result = subprocess.run(
            [sys.executable, "-m", "pdoc", "neuraldbg", "--output-dir", str(tmp_path)],
            capture_output=True,
            text=True,
        )
        assert (
            result.returncode == 0
        ), f"pdoc failed with exit {result.returncode}:\n{result.stderr}"

    def test_docs_output_file_created(self, tmp_path):
        """pdoc produces an HTML file for the neuraldbg module."""
        subprocess.run(
            [sys.executable, "-m", "pdoc", "neuraldbg", "--output-dir", str(tmp_path)],
            capture_output=True,
        )
        html_files = list(tmp_path.glob("*.html"))
        assert len(html_files) >= 1, "No HTML file generated by pdoc"

    def test_all_public_methods_documented(self, tmp_path):
        """All main public methods of NeuralDbg appear in the generated HTML."""
        subprocess.run(
            [sys.executable, "-m", "pdoc", "neuraldbg", "--output-dir", str(tmp_path)],
            capture_output=True,
        )
        html_files = list(tmp_path.glob("*.html"))
        assert html_files, "No HTML generated — cannot check method coverage"

        combined = "".join(f.read_text() for f in html_files)
        missing = [m for m in REQUIRED_METHODS if m not in combined]
        assert not missing, f"Methods absent from generated docs: {missing}"
