name: Post Release
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Ensures CHANGELOG.md is accessible

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Matplotlib 3.8+ requires Python ≥3.9

      - name: Install Dependencies
        run: |
          pip install tweepy python-dotenv  # Add python-dotenv if using .env files

      - name: Post Release Tweet
        env:
          # Verify these secrets exist in GitHub repo settings:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          # Strip 'v' from version if tags are like "v1.2.3"
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          python -c "from twitter_bot import post_release; post_release('$VERSION')"