name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov selenium webdriver-manager

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromedriver

      - name: Start NeuralDbg Dashboard (Background)
        run: |
          python dashboard.py & sleep 5

      - name: Run Backend Tests (Pytest)
        run: pytest --cov=neural --cov-report=xml

      - name: Run UI Tests (Selenium)
        run: pytest tests/ui_tests.py --disable-warnings

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml

      - name: Send Alert on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"🚨 Tests Failed in NeuralDbg CI! Check GitHub Actions for details."}' ${{ secrets.DISCORD_WEBHOOK_URL }}
