# .github/workflows/create_issues.yml
name: Automate Pytest Bugs to GitHub Issues
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_and_create_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pygithub
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Install project in editable mode
        run: |
          pip install -e .

      - name: Run tests with XML
        continue-on-error: true
        run: |
          pytest tests/ --junit-xml=test-results.xml || echo "Pytest failed but continuing"
        
      - name: Create XML if missing
        if: always()
        run: |
          if [ ! -f test-results.xml ]; then
            echo '<?xml version="1.0"?><testsuite name="pytest" errors="1"><testcase name="dummy"><error message="No tests executed"/></testcase></testsuite>' > test-results.xml
          fi
        
      - name: Create GitHub Issues for Failures
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUES_TOKEN }}
        run: |
          python scripts/create_issues.py

      - name: Debug Test Results
        if: always()
        run: |
          echo "=== XML File Exists ==="
          ls -l test-results.xml
          echo "=== XML Content ==="
          cat test-results.xml
          echo "=== Environment ==="
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN != '' }}"
